### ISSUE TITLE
Components not in Default Theme

### ISSUE THREAD

**Issue by hallahan** [GitbookIO/styleguide#13]
Hi Gitbook Folks!

First of all, awesome web publishing framework, really enjoy using it.

Looking at your guide, I'm trying to use components in my GItbook using the default theme, but it doesn't seem like the LESS is included by default. How do you best suggest I include the LESS behind the styleguide described?

**Comment by hallahan** [comment]
For example, I need to utilize a grid system for some divs, but the grid system specified here does not work. It looks like the default theme does not actually have a portion of the style guide. Any tips on how to integrate this into default theme would help.

**Comment by SamyPesse** [comment]
Sorry for the very late response.

This styleguide is not designed for books, it's being used for GitBook.com and the GitBook Editor.
