### ISSUE TITLE
[Question] Why copying GitHub's style?

### ISSUE THREAD

**Issue by vapits** [GitbookIO/styleguide#26]
First of all I would like to give you my congrats for the service, it's awesome and I would like to use it a lot both for personal but also business purposes.

Now my question i guess is self explanatory and it doesn't only fit on the styling but I guess it's a good place to start.

As I already told I would like to use the service but I have concerns regarding the copy of styling of GitHub. The reason is quite simple, first of all this is not a github's project (correct?) and secondary I guess there can be a conflict with gitHub in the future and therefore you can have legal issues with them and again therefore then the users of GitBook could face a problem, that they will have to transfer elsewhere there content.

What's your opinion on this?

Thanks again!

**Comment by SamyPesse** [comment]
Hi @vapits 

We are not trying to copy GitHub's style, but I have to admit that GitHub is an important source of inspiration to us ("Imitation is the sincerest form of flattery").

We have discussions internally about how to create our own visual identity, this is something that we truly want to achieve and we are actively working on it; this styleguide was the first step in this direction.

As GitBook evolves, its identity will become more defined and separated from GitHub.
